language: java

dist: trusty
sudo: false

script:
  - ./gradlew -version
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./dev/check_and_deploy.sh

OSSRH_USER:
  secure: jgkDtm+LqKLpqoleEV2fX9fALjzwOG8n3RwLFpDfzIsGDhCQ9i2H9TKxGDzGiN8lcdVqKhl8a+Zj+gKjIqNvM+zB0Np7JF1C/oCJzKaNHvZizw+obABTm58PyPsuZP3mZuqpsgCNuXFNSaJ13t3rBeXPIdhrtr8Xb66Rdv2cIxa7NlHi2FsEf+c2EcIuxkoizcqmkDTa9aSHpCwZ6N3lqgynHZHhbkuLC10nr4PKdvgL/FixAwT1NCis+95E30gM6BTBxvhmUU9IVy2DfvJ6um1bykZ7ziBLm/lY5LOru4Ei23loD7H49me2y2rjecgbzV1yr2re5o2psERrKd9Y+zRyCM8i/FsX5qk6C6ua+ZXP1XJyVO9yE7usgUktcj9qxcaw/AaRuimBINvRFXKKw21fdyf4ahnaOpMpBYZEvXkRZdhZ7V/43HeO7PNAH2UzHliXaoK9fQcnRMYUjpB2bCTVb8LtLB9ApsJJ0/a8fPGhkMfLvx/NVtQNlLnAdx6nvgYD6iOo9Ux1Fyf11ZnrSJVSZ8SU0i0JkhY7fB3KkwP5+LHWIMxw0LMNY1cCCtrDt6Imn0Rw1OCwavADYqG+W+WQrszCaAurcW80xTYYrsbXDfu8BqWtLIk7KCWzVw+nOHlXXkZc0ffCO52D0yAcwqbluC6FeTJ0LzEqJrIeiVU=
OSSRH_PASS:
  secure: EuH4PsNrbehh7r+B1gIKEwgpAqkToJwX7WbzQ1+4/++ugf+HwTTw3+a+recAJDnwF9gzWVHIjR3YDAO7jesvPKXtdhsOibfB6oJdNc3yd0ANkXdFBRD5TloKPX6vERlRCI5PnL7QUibN3l9CbPf+idlbwIErosYaUgsnKz+JdPF6JJxyEYnUZ7+lTRmx3FKhPF+biQgu8HsJtT3dtDxjXKE2t7cGa6UaNz17nB5YxsWUIxS2oaBBtqaanit+YSaXkkWBgxRuM4S4IzVh/6Ne2oFED7QNJJsWL4opAd5+cK1Lnn1FvDVQCGDx3SRvZOc4L+d20i/Ytn0JkO9pGtwVVSWgGwW2RkZzlkiFWKym7ap99oKsL/twAVAyytPiNMWATE0vzO4BPrSkFnWOMzFgLRWM0ObfrhW7oOmu9iNeTjEM4CfARMS/5yePaNYQFga/izzSH01brWUbP7RtKHdk0JsJa2Y4c+ILbGMU6HSEct/6NDQitBZUr0INYaGJqxIdwHYhq7kq7hP8ypu4LJLm4LxwE0xz5xs+x+IpXQHtTzXZ03+RJl78IOwogEc9vTZmVE7ECE4yKf08Fpf5xY+kyVVgS5rGzYgWYXcaRM4GkbFdAKtPL8VC0KtL9GXacUqo34vqqsFJ/XpaHPoHCDH9mkTXgzGQf5YZ4VUipPO3LIU=
